version: '3'
services:
  ts-test-db:
    image: mariadb
    container_name: ts-test-db
    # volumes:
    #   # Make database persistent
    #   - /var/lib/mysql
    environment:
      MYSQL_DATABASE: ts-test-db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: tstest
      MYSQL_PASSWORD: tstest
    ports:
      - 3306:3306
